services:
  - type: web
    name: tendervault-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEPLOYER_MNEMONIC
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ALGORAND_APP_ID
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
